// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLqDn2gWF7fEuZ7V0Oy2_GQZ4u5glrVlQ',
    appId: '1:365613157847:web:7413cfdd0b63cdc37a0f92',
    messagingSenderId: '365613157847',
    projectId: 'ticketavion-bf30e',
    authDomain: 'ticketavion-bf30e.firebaseapp.com',
    storageBucket: 'ticketavion-bf30e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFqwhzYkefoYvF3l6xjb0aGtAW7EbPjE8',
    appId: '1:365613157847:android:cfbc59236b08e5eb7a0f92',
    messagingSenderId: '365613157847',
    projectId: 'ticketavion-bf30e',
    storageBucket: 'ticketavion-bf30e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLhHNgTFG4Vm1rxMYB2vhC75g5BVx1G1A',
    appId: '1:365613157847:ios:2ce81da813c90b757a0f92',
    messagingSenderId: '365613157847',
    projectId: 'ticketavion-bf30e',
    storageBucket: 'ticketavion-bf30e.appspot.com',
    iosBundleId: 'com.example.examen2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLhHNgTFG4Vm1rxMYB2vhC75g5BVx1G1A',
    appId: '1:365613157847:ios:2ce81da813c90b757a0f92',
    messagingSenderId: '365613157847',
    projectId: 'ticketavion-bf30e',
    storageBucket: 'ticketavion-bf30e.appspot.com',
    iosBundleId: 'com.example.examen2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLqDn2gWF7fEuZ7V0Oy2_GQZ4u5glrVlQ',
    appId: '1:365613157847:web:a7dc720872e88bcb7a0f92',
    messagingSenderId: '365613157847',
    projectId: 'ticketavion-bf30e',
    authDomain: 'ticketavion-bf30e.firebaseapp.com',
    storageBucket: 'ticketavion-bf30e.appspot.com',
  );
}
